name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Setup cargo target deps
        run: |
          sudo apt-get update && sudo apt-get install -y musl-tools
      - name: Build Linux (musl)
        run: |
          rustup target add x86_64-unknown-linux-musl
          cargo build --release --target x86_64-unknown-linux-musl
      - name: Build Windows
        run: |
          rustup target add x86_64-pc-windows-gnu
          cargo build --release --target x86_64-pc-windows-gnu
      - name: Build macOS (on mac runner in separate job)
        if: false
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lss-binaries
          path: |
            target/x86_64-unknown-linux-musl/release/lss
            target/x86_64-pc-windows-gnu/release/lss.exe
